# Generated by Django 3.2.9 on 2021-11-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workout1_time', models.DurationField()),
                ('workout2_time', models.DurationField()),
                ('workout3_time', models.DurationField()),
                ('workout4_time', models.DurationField()),
            ],
        ),
    ]
