# Generated by Django 3.2.9 on 2021-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20211126_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
