# Generated by Django 3.2.9 on 2021-11-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_participant_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='workout1_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='workout2_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='workout3_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='workout4_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=4),
        ),
    ]
